#pragma once

enum ReceiveCode {
	ID_ACCEPT_USER = 5,
	ID_REFUSE_USER = 6,
	ID_INVALID_NAME = 7,
	ID_DUPLICATE_NAME = 8,
	ID_GAME_INFO = 9,
	ID_START_GAME = 10,
	ID_PING = 11,
	ID_CUR_PLAYER = 12,
	ID_TRUE_ANSWER = 13,
	ID_WRONG_ANSWER = 14,
	ID_WIN_GAME = 15,
	ID_WIN_ANNOUNCE = 16,
	ID_QUESTION = 17,
	ID_ALLOWED_MOVE = 18,
};
enum SendCode {
	ID_USER_NAME = 5,
	ID_ANSWER = 6,
	ID_MOVE = 7,
	ID_PING_ANS = 8,
};